
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - MONGODB_URI=mongodb://root:root@mongodb:27017/admin?authSource=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - /usr/src/app/node_modules
      - ./backend/src:/usr/src/app/backend/src
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    restart: unless-stopped
    volumes:
      - /usr/src/app/node_modules
      - ./frontend/src:/usr/src/app/frontend/src



  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./backend/db:/data/db

